DELIMITER |

DROP TRIGGER IF EXISTS `AutoMinMaxTeleinfoUpdInst` |

CREATE DEFINER=`teleinfo`@`localhost` TRIGGER `AutoMinMaxTeleinfoUpdInst`

AFTER UPDATE ON `T_TELEINFO_INST`

FOR EACH ROW

BEGIN

   DECLARE OLD_PAPP_MIN INTEGER ;

   DECLARE OLD_PAPP_MAX INTEGER ;
  
   DECLARE TS_DATE DATE ;

   DECLARE TS_TIME TIME ;

   DECLARE DeletedNb INTEGER ;

   DECLARE InsertedNb INTEGER ;
   
   UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxTeleinfoRunNb = T_COUNTERS.AutoMinMaxTeleinfoRunNb + 1, T_COUNTERS.AutoMinMaxTeleinfoLastRunTs = NOW() ;
   
   SET @TS_DATE = DATE( NEW.TS ) ;

   SET @TS_TIME = TIME( NEW.TS ) ;

   INSERT T_TELEINFO_MIN SET TS_DATE = @TS_DATE, TS_TIME = @TS_TIME, PAPP = 10000000, IINST = 10000000 ON DUPLICATE KEY UPDATE Id = Id ; 
   
   SET @InsertedNb = ROW_COUNT() ;
   
   UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxTeleinfoMinInsNbTotal = T_COUNTERS.AutoMinMaxTeleinfoMinInsNbTotal + @InsertedNb ;
   
   INSERT T_TELEINFO_MAX SET TS_DATE = @TS_DATE, TS_TIME = @TS_TIME, PAPP = 0, IINST = 0 ON DUPLICATE KEY UPDATE Id = Id ; 
   
   SET @InsertedNb = ROW_COUNT() ;
   
   UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxTeleinfoMaxInsNbTotal = T_COUNTERS.AutoMinMaxTeleinfoMaxInsNbTotal + @InsertedNb ;
  
   SET @OLD_PAPP_MIN = ( SELECT PAPP FROM T_TELEINFO_MIN WHERE T_TELEINFO_MIN.TS_DATE = @TS_DATE ) ;

   SET @OLD_PAPP_MAX = ( SELECT PAPP FROM T_TELEINFO_MAX WHERE T_TELEINFO_MAX.TS_DATE = @TS_DATE ) ;
   
   IF NEW.PAPP < @OLD_PAPP_MIN

   THEN

      UPDATE T_TELEINFO_MIN SET T_TELEINFO_MIN.PAPP = NEW.PAPP, T_TELEINFO_MIN.IINST = NEW.IINST, T_TELEINFO_MIN.TS_TIME = @TS_TIME WHERE T_TELEINFO_MIN.TS_DATE = @TS_DATE ;
      
      UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxTeleinfoMinUpdNbTotal = T_COUNTERS.AutoMinMaxTeleinfoMaxInsNbTotal + 1 ;

   END IF ;
   
   IF NEW.PAPP > @OLD_PAPP_MAX

   THEN

      UPDATE T_TELEINFO_MAX SET T_TELEINFO_MAX.PAPP = NEW.PAPP, T_TELEINFO_MAX.IINST = NEW.IINST, T_TELEINFO_MAX.TS_TIME = @TS_TIME WHERE T_TELEINFO_MAX.TS_DATE = @TS_DATE ;
      
      UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxTeleinfoMaxUpdNbTotal = T_COUNTERS.AutoMinMaxTeleinfoMaxUpdNbTotal + 1 ;

   END IF ;

   DELETE FROM T_TELEINFO_MIN WHERE TS_DATE < DATE_SUB( NOW(), INTERVAL 120 DAY ) ;

   SET @DeletedNb = ROW_COUNT() ;
   
   UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxTeleinfoMinDelNbTotal = T_COUNTERS.AutoMinMaxTeleinfoMinDelNbTotal + @DeletedNb ;
   
   DELETE FROM T_TELEINFO_MAX WHERE TS_DATE < DATE_SUB( NOW(), INTERVAL 120 DAY ) ;

   SET @DeletedNb = ROW_COUNT() ;
   
   UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxTeleinfoMaxDelNbTotal = T_COUNTERS.AutoMinMaxTeleinfoMaxDelNbTotal + @DeletedNb ;

END |

DELIMITER ;
