DELIMITER |

DROP TRIGGER IF EXISTS AutoMinMaxInsertHisto |

CREATE TRIGGER AutoMinMaxInsertHisto AFTER INSERT

ON T_TELEINFO_HISTO FOR EACH ROW

BEGIN

   DECLARE OLD_PAPP_MIN INTEGER ;

   DECLARE OLD_PAPP_MAX INTEGER ;
  
   DECLARE TS_DATE DATE ;

   DECLARE TS_TIME TIME ;

   DECLARE DeletedNb INTEGER ;

   DECLARE InsertedNb INTEGER ;

   SET @TS_DATE = DATE( NEW.TS ) ;

   SET @TS_TIME = TIME( NEW.TS ) ;

   INSERT T_TELEINFO_MINMAX SET TS = @TS_DATE, PAPP_MIN = 99999, IINST_MIN = 99999, PAPP_MAX = 0, IINST_MAX = 0 ON DUPLICATE KEY UPDATE Id = Id ; 

   SET @InsertedNb = ROW_COUNT() ;

   UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxHistoInsNbTotal = T_COUNTERS.AutoMinMaxHistoInsNbTotal + @InsertedNb ;
  
   SET @OLD_PAPP_MIN = ( SELECT PAPP_MIN FROM T_TELEINFO_MINMAX WHERE TS = @TS_DATE ) ;

   SET @OLD_PAPP_MAX = ( SELECT PAPP_MAX FROM T_TELEINFO_MINMAX WHERE TS = @TS_DATE ) ;
	
   IF NEW.PAPP > @OLD_PAPP_MAX

   THEN

      UPDATE T_TELEINFO_MINMAX SET T_TELEINFO_MINMAX.IINST_MAX = NEW.IINST, T_TELEINFO_MINMAX.PAPP_MAX = NEW.PAPP, T_TELEINFO_MINMAX.TS_MAX = @TS_TIME, T_TELEINFO_MINMAX.TEMP_MAX = NEW.TEMPERATURE, T_TELEINFO_MINMAX.RH_MAX = NEW.RH WHERE TS = @TS_DATE ;

      UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxHistoUpdMaxNbTotal = T_COUNTERS.AutoMinMaxHistoUpdMaxNbTotal + 1 ;

   END IF ;

   IF NEW.PAPP < @OLD_PAPP_MIN

   THEN

      UPDATE T_TELEINFO_MINMAX SET T_TELEINFO_MINMAX.IINST_MIN = NEW.IINST, T_TELEINFO_MINMAX.PAPP_MIN = NEW.PAPP, T_TELEINFO_MINMAX.TS_MIN = @TS_TIME, T_TELEINFO_MINMAX.TEMP_MIN = NEW.TEMPERATURE, T_TELEINFO_MINMAX.RH_MIN = NEW.RH WHERE TS = @TS_DATE ;

      UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxHistoUpdMinNbTotal = T_COUNTERS.AutoMinMaxHistoUpdMinNbTotal + 1 ;

   END IF ;

   UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxHistoRunNb = T_COUNTERS.AutoMinMaxHistoRunNb + 1, T_COUNTERS.AutoMinMaxHistoLastRunTs = NOW() ;

   DELETE FROM T_TELEINFO_MINMAX WHERE TS < DATE_SUB( NOW(), INTERVAL 8 DAY ) ;

   SET @DeletedNb = ROW_COUNT() ;

   UPDATE T_COUNTERS SET T_COUNTERS.AutoMinMaxHistoDelNbTotal = T_COUNTERS.AutoMinMaxHistoDelNbTotal + @DeletedNb ;

END |

DELIMITER ;
